############################
# GitHub Actions Workflow #
###########################

name: Java CI with Maven

on:
  push:
    paths-ignore:
     - 'README.md'
     - 'LICENSE.md'
     - '**.pdf'
  pull_request:
    paths-ignore:
     - 'README.md'
     - 'LICENSE.md'
     - '**.pdf'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      workdir: spring-bookshelf
    steps:

    - name: Clone the GitHub repo in the Runner
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 11 in the Runner
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Cache Maven packages and SonarQube artifacts
      uses: actions/cache@v2
      with:
        path: |
          ~/.m2
          ~/.sonar/cache
        key: ${{ runner.os }}-m2-${{ hashFiles('**/spring-bookshelf/pom.xml', '**/*.yml') }}
        restore-keys: ${{ runner.os }}-m2-

    - name: Run Unit Tests (with JaCoCo)
      run: ../mvnw verify -Pjacoco
      working-directory: ${{ env.workdir }}

    - name: Run Integration Tests in a separate build
      run: ../mvnw verify -Pit-tests
      working-directory: ${{ env.workdir }}

    - name: Send code coverage report (previously collected) to Coveralls
      run: >
        ../mvnw coveralls:report
        -DrepoToken=$COVERALLS_REPO_TOKEN
        -DpullRequest=${{ github.event.pull_request.number }}
      working-directory: ${{ env.workdir }}
      env: 
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}

    - name: Run End-to-end tests in a separate build
      run: xvfb-run ../mvnw verify -Pe2e-tests
      working-directory: ${{ env.workdir }}

    - name: Run SonarQube analysis through SonarCloud
      run: >
        ../mvnw sonar:sonar
        -Dsonar.organization=francescomucci
        -Dsonar.host.url=https://sonarcloud.io
      working-directory: ${{ env.workdir }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

